#!/bin/sh

# DEPENDENCIES:
# 1. fzf
# 2. BROWSER environment variable

bookmark_file="$HOME/.local/data/bookmarks"

if ! [ -f "$bookmark_file" ]; then
	printf "Error: file not found '%s'\n" "$bookmark_file"
	exit 1
fi

if [ -z "$BROWSER" ]; then
	printf "Error: BROWSER environment variable is not set\n"
	exit 1
fi

prompt="Visit in ${BROWSER}"

if [ "$1" = "-r" ]; then
    url=$(column -s'|' -t "$bookmark_file" \
	      | rofi -dmenu -l25 -i  -p "$prompt" \
	      | sed 's/.*\s//')

else

url=$(column -s'|' -t "$bookmark_file" \
	  | fzf --prompt "$prompt > " \
		--layout=reverse \
		--border=rounded \
	  | sed 's/.*\s//')

fi

if [ -n "$url" ]; then
    nohup $BROWSER --new-tab "$url" > /dev/null 2>&1 < /dev/null &
    sleep 0.05
fi
