#!/bin/sh

# Dependencies:
# 1. dmenu
# 2. BROWSER environment variable

bookmarks_file="$HOME"/.local/data/bookmarks

url=$(column -s'|' -t "$bookmarks_file" | dmenu -i -c -p "Visit in ${BROWSER}" -l 15 | sed 's/\s.*//')

if [ -n "$url" ]; then
    $BROWSER --new-tab "$url" > /dev/null 2>&1 &
fi
