#!/bin/sh

# Note: I launch this script through a dropdown terminal.

# Directory where I store pdf of books
booksDir="/data/Documents/Books"

cd "$booksDir" || exit 1

# present the book list in `fzf`
selectedBook=$(find -type f -name *.pdf | sed 's,\./,,1' | fzf)

# open the pdf in `zathura`
[ -n "$selectedBook" ] && zathura $selectedBook &
