#!/bin/sh

# Dependencies:
# 1. brightnessctl
# 2. dunst

icon="$XDG_CONFIG_HOME"/dunst/icons/brightness.png
id=1823

send_notification()
{
    brightness=$(brightnessctl -c backlight -m | cut -d',' -f4)
    dunstify -i "$icon" -r $id "Brightness" "$brightness" &
}

case "$1" in
    up)
	brightnessctl --class=backlight --quiet set 1%+
	send_notification
	;;

    down)
	brightnessctl --class=backlight --quiet set 1%-
	send_notification
	;;
esac
