#!/bin/sh

remote_ip=$(ip -br neigh show | cut -d' ' -f1 \
		| fzf --height=15 \
		      --layout=reverse \
		      --prompt="Connect with ssh > ")

if [ -z "$remote_ip" ]
then
    printf "Remote IP address not found.\n"
    exit 1
fi

printf "Connecting to: %s ...\n" $remote_ip

exec ssh -p 8022 -o 'StrictHostKeyChecking=no' $remote_ip
