#!/bin/sh

# Dependencies:
# 1. dmenu
# 2. READER environment variable

documents_dir="$HOME"/Documents

cd "$documents_dir" || exit 1

document=$(find -type f -iname '*.pdf' | sed 's,^\./,,1' | dmenu -i -c -p "Open in ${READER}" -l 15)

[ -n "$document" ] && $READER "$document" &
