#!/bin/sh
#
# Presents a list of fonts in dmenu, and copies the selection into
# the system clipboard.
#

selection=$(fc-list | cut -d':' -f2,3 | column -s':' -t -- | dmenu -i -c -l 15 -p 'Select font')

fontname=$(printf '%s' "$selection" | sed 's/ *style=.*//')

printf '%s' "$fontname" | xclip -selection clipboard
