#!/bin/sh

set -e
project_type="$1"
project_name="$2"

if [ $# -eq 0 ]; then
    printf "USAGE: %s [c|cpp|js] project-name\n" "$0"
    exit 1
elif [ -d "$project_name" ]; then
    printf "ERROR: %s directory already exists\n" "$1"
    exit 1
else
    /usr/bin/mkdir -p "$project_name"
    cd "$project_name"
    git init . > /dev/null
    touch .gitignore LICENSE README.org
    case "$project_type" in
	c)
	    touch Makefile
	    printf "*.o\n${project_name}\n*~" >> .gitignore
	    printf "CompileFlags:
 Add: [-Wall, -Werror, -Wshadow, -pedantic, -std=c11, -Wno-nonull]
" > .clangd
	    ;;

	cpp)
	    touch Makefile
	    printf "*.o\n${project_name}\n*~" >> .gitignore
	    printf "CompileFlags:
 Add: [-Wall, -Werror, -Wshadow, -pedantic, -std=c++17, -Wno-nonull]
" > .clangd
	    ;;

	js)
	    printf ".log\nnode_modules\n*~" >> .gitignore
	    npm init -y > /dev/null
	    ;;
    esac
    printf "INFO: project initliazed in: %s\n" "$1"
    return 0
fi
