#!/usr/bin/env bash

# opusmv takes one opus file as argument and moves it inside of a folder named
# after the ALBUM of the track.

if [ $# -eq 0 ]; then
    echo "Usage: opusmv FILE"
    exit 1
fi

move_opus_file ()
{
    album=$(opustags "$1" | grep -iF "album=" | sed 's/^.*=//')
    if [ -z "$album" ]; then
        >&2 echo "file has no ALBUM tag: " "$1"
        exit 1
    fi
    folderName=$(printf "%s" "$album" | tr -c [:alnum:] '-')
    [ -z "$folderName" ] && exit 1
    mkdir -p "$folderName"
    mv "$1" "$folderName/"
}

move_opus_file "$1"
