#!/bin/sh

# Dependencies:
# 1. grim  - the program that captures screensots
# 2. slurp - the program that selectes screen area
# 3. A notification program

screenshotsDir="$(xdg-user-dir PICTURES)/screenshots"

if ! [ -d "$screenshotsDir" ]
then
    mkdir -p "$screenshotsDir" || screenshotsDir="$HOME"
fi

fileName=$(date +"%s").png
filePath="$screenshotsDir"/"$fileName"

if [ "$1" = "--selection" ]
then
    grim -l0 -g "$(slurp)" "$filePath"
else
    grim -l0 "$filePath"
fi

# copy image to clipboard
wl-copy < "$filePath"

action=$(notify-send "Screenshot Saved" "as $fileName and copied to clipboard" \
                     --app-name="Screenshot" --icon="camera" \
		     --action "default=Open screenshot in image viewer")

case "$action" in
    "default")
	imv -s shrink "$filePath" &
	;;
esac
