#!/bin/sh

# Dependencies:
# 1. maim  - the program that captures screensots
# 2. dunst - notification program

screenshots_dir="$HOME"/Pictures/Screenshots
file_name=$(date +"%s").png
icon="$XDG_CONFIG_HOME"/dunst/icons/screenshot.png

if ! [ -d "$screenshots_dir" ]
then
    mkdir -p $screenshots_dir || screenshot_dir="$HOME"
fi

if [ "$1" = "-s" ]
then
    maim -u -s "$screenshots_dir/$file_name"
else
    maim -u "$screenshots_dir/$file_name"
fi

dunstify -i $icon "Screenshot Taken" &
