#!/bin/sh

DAY=$(date +"%A")

case $DAY in
    Monday)
		# TOC on Monday    12:00 – 2:00pm 
		firefox --new-tab "https://meet.google.com/nbq-dpcw-kjj" > /dev/null 2>&1 &
		;;
    Tuesday)
		# TOC on Tuesday   11:00am – 12:00pm 
		firefox --new-tab "https://meet.google.com/qmo-kjhf-zcz" > /dev/null 2>&1 &
		;;
    Wednesday)
		# TOC on Wednesday 12:00 – 1:00pm
		firefox --new-tab "https://meet.google.com/qmo-kjhf-zcz" > /dev/null 2>&1 &
		;;
    Thursday)
		# TOC on Thursday 12:00 – 1:00pm
		firefox --new-tab "https://meet.google.com/qmo-kjhf-zcz" > /dev/null 2>&1 &
		;;
    Friday)
		# TOC on Friday   12:00 – 2:00pm 
		firefox --new-tab "https://meet.google.com/phd-daqz-hks" > /dev/null 2>&1 &
		;;
    *)
		echo "No TOC today. Enjoy."
		exit 0
		;;
esac

# open TOC book
BOOK="/data/Documents/Books/Others/Introduction_to_Computer_Theory_2nd_Edition_by_Daniel_Cohen.pdf"
[ -f "$BOOK" ] && zathura "$BOOK" &

