#!/usr/bin/env bash

variant="$(gsettings get org.gnome.desktop.interface color-scheme)"

if [[ "$variant" =~ "prefer-light" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface icon-theme Papirus-Dark
    gsettings set org.gnome.desktop.interface gtk-theme Arc-BLACKEST
else
    gsettings set org.gnome.desktop.interface color-scheme prefer-light
    gsettings set org.gnome.desktop.interface icon-theme Papirus-Light
    gsettings set org.gnome.desktop.interface gtk-theme Gruvbox-Light
fi

emacsclient --eval '(ef-themes-toggle)'
